### PR TITLE
Remove overlapping generated tests, closes #535

### LINKED ISSUE #535: Compute overlap between the generated tests to generate fewer tests
Right now DSpot generate new tests independently of one another, i.e. each test is generated and have its mutation score compared to the original baseline and if the mutation score is greater then the new test is kept. This leads to having a lot of new tests added that are the same (see below).

One idea would be that once DSpot succeeds in generating a new test, this new test is added to the baseline and thus new tests need to increase the mutation score of that new baseline to not be discarded.

For example 2 new tests have been generated in on some XWiki module:

In ProviderTest:

```
    public void loadAndInjectProviderWhenExceptionInInitialize() throws Exception {
        EmbeddableComponentManager cm = new EmbeddableComponentManager();
        Assert.assertNull(((EmbeddableComponentManager) (cm)).getParent());
        Assert.assertNull(((EmbeddableComponentManager) (cm)).getNamespace());
        Assert.assertNull(((EmbeddableComponentManager) (cm)).getComponentEventManager());
        cm.initialize(getClass().getClassLoader());
...
```

In EmbeddableComponentManagerTest:

```
    @Test(timeout = 10000)
    public void testUnregisterDisposableSingletonComponentWithInstance() throws Exception {
        EmbeddableComponentManager ecm = new EmbeddableComponentManager();
        Assert.assertNull(((EmbeddableComponentManager) (ecm)).getParent());
        Assert.assertNull(((EmbeddableComponentManager) (ecm)).getComponentEventManager());
        Assert.assertNull(((EmbeddableComponentManager) (ecm)).getNamespace());
        DefaultComponentDescriptor<EmbeddableComponentManagerTest.Role> cd = new DefaultComponentDescriptor<EmbeddableComponentManagerTest.Role>();
...
```
In practice we don't need that DSpot generates new tests wherever it finds `EmbeddableComponentManager ecm = new EmbeddableComponentManager();` by adding the 3 asserts... This won't increase the test coverage nor the mutation score. But it will increase the test execution time if we want to include automatically all the tests that DSpot generates.

Thus it would be nice to have an option for this :)

Thx

### PR DESCRIPTION
**Pull request by andrewbwogi**

### CODE REVIEW

**Comment by danglotb** [comment]
Hello @andrewbwogi 

Could resolve the conflicts in order to merge this pull request and make the announced release #758.

**Comment by andrewbwogi** [comment]
I've created test cases that produce overlapping tests and the selectors remove the redundant tests. I'm currently abstracting common features of the new test classes and organizing them in the style of earlier selector tests.

**Comment by andrewbwogi** [comment]
Hi @danglotb, how can I see and reproduce what is failing in the CI build?

**Comment by danglotb** [comment]
Hello @andrewbwogi 

The details of the build are available [here](https://travis-ci.org/STAMP-project/dspot/builds/527215999?utm_source=github_status&utm_medium=notification). (click on the detail button next to the line of travis)

There are 3 builds that fail, but it is probably the same errors since it uses different jdk or computes the coverage.

The errors are:

```txt
Failed tests:   testExample(eu.stamp_project.MainTest): expected:<...cation results with [22] amplified tests.(..)

Tests in error: 
  testRemoveOverlappingTests(eu.stamp_project.dspot.selector.PitScoreMutantSelectorTest): java.lang.RuntimeException: java.io.FileNotFoundException: src/test/resources/regression/test-projects_2/test-projects.properties (No such file or directory)
  testRemoveOverlappingTests(eu.stamp_project.dspot.selector.JacocoCoverageSelectorTest): java.lang.RuntimeException: java.io.FileNotFoundException: src/test/resources/regression/test-projects_2/test-projects.properties (No such file or directory)

Tests run: 191, Failures: 1, Errors: 2, Skipped: 6
```

I let you investigate.

**Comment by danglotb** [comment]
Changes seem good to me, ready to merge?

**Comment by andrewbwogi** [comment]
Yes, you can merge.

**Pull request merged**
