### PR TITLE
test: update Gradle Automatic Builder

### PR DESCRIPTION
**Pull request by danglotb**

### CODE REVIEW

**Comment by danglotb** [comment]
@monperrus Should fix SOS. Sorry for the delay.

**Comment by monperrus** [comment]
Thanks a lot @danglotb

**Comment by monperrus** [comment]
FYI SOS not fixed ` GradleAutomaticBuilderWithDescartesTest.setUp:56 » Runtime java.io.IOException...`

See https://ci.inria.fr/sos/job/dspot/148/console

WDYT?

**Comment by danglotb** [comment]
Thank you for the info.

It looks like `gradle` is not installed on the node:

```txt
java.lang.RuntimeException: java.io.IOException: Cannot run program "gradle" (in directory "/builds/workspace/dspot/dspot/src/test/resources/test-projects"): error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at eu.stamp_project.dspot.common.automaticbuilder.gradle.GradleAutomaticBuilder.runTasks(GradleAutomaticBuilder.java:120)
	at eu.stamp_project.dspot.common.automaticbuilder.gradle.GradleAutomaticBuilder.compile(GradleAutomaticBuilder.java:60)
	at eu.stamp_project.dspot.common.automaticbuilder.gradle.GradleAutomaticBuilderWithDescartesTest.setUp(GradleAutomaticBuilderWithDescartesTest.java:56)
```

I see three ways to get out of this:
1. `@Ignore` the test on `GradleAutomaticBuilder`
2. Try to install `gradle` on the node
3. Find another way to fix the original issue.

I prefer the first option because this feature is not the core of DSpot and a bit in extra. I would love to remove it from DSpot. WDYT?

**Comment by monperrus** [comment]
OK for me to @Ignore the tests of GradleAutomaticBuilder. Would you do a PR? Thanks!

**Pull request merged**
