### PR TITLE
Feat: parallelize dspot on Kubernetes (#802)

### PR DESCRIPTION
**Pull request by Tailp**
Hi, this PR contains necessary files for deploying Dspot on Kubernetes in reference to this issue (#802). For more details please check out the readme at this [link](https://github.com/Tailp/dspot/tree/kubernetes/kubernetes) :) . Tell me also if there are any problems to fix.

### CODE REVIEW

**Comment by danglotb** [comment]
Looks good to me.

However, I don't get the point with the two Travis. Where is the difference between [without_dspot](https://travis-ci.org/Tailp/travisplay/builds/551693890) and [with_dspot](https://travis-ci.org/Tailp/travisplay/builds/551741145)? Both traces look exactly the same.

Thank you!

**Comment by Tailp** [comment]
Hi @danglotb , ah sorry I might have missed out elaborating that. The difference is in the pom.xml file . I assume that if people know about this technology then they would add dspot as maven dependency rather than using a jar file :) . The difference between the pom files is down below to spare you the trouble looking up.

´´´
   <plugins>
        <plugin>
          <groupId>eu.stamp-project</groupId>
          <artifactId>dspot-maven</artifactId>
          <version>2.1.0</version>
          <configuration>
            project=.
            targetModule=.
            src=src/main/java
            testSrc=src/test/java
            javaVersion=8
          </configuration>
        </plugin>
    </plugins>

´´´

Cheers  :)

**Comment by danglotb** [comment]
Hello @Tailp 

Okay, I saw the difference.

But If I get it right, the Travis build should trigger dspot on your project, right? But I can't see this execution.

Thus, IHMO your dspot's configuration is probably wrong since it looks like you are defining properties (that should be defined in a separate file `.properties`) in your `pom`.

Best

**Comment by Tailp** [comment]
Hi @danglotb :),

An example procedure can be like this for the stand-alone dspot without repairnator: 

* A dev or some other programs can submit a travis build id on the ActiveMQ using the script "publisher.py" in this [folder](https://github.com/Tailp/dspot/tree/kubernetes/kubernetes/queue-for-buildids)

* Then since we have several dspot instances listening to this queue, it will pull the travis build id from the queue and fetch the repository (with correct git branch ofcourse) related to that build id. 

* Then it will run the usual Dspot on the cloned repo as a subprocess (more details in this [script](https://github.com/Tailp/dspot/blob/kubernetes/kubernetes/Dpipeline-dockerimage/Dpipeline_worker.py) and submit the output files on mongodb when done.

If this is paired together with repairnator, you can add a gitwebhook on the repo and when travis build is done running it will trigger the monitor to analyze the repo and fetch the recent build Id which either sent to repairnator if the travis build failed for repairing or further amplication using Dspot upon success. The design for this monitor is in [here](https://github.com/gluckzhang/repairnator/tree/kubernetes/repairnator/docker-images/kubernetes)

I need to discuss this with @monperrus  later about whether we should modify the repairnator scanner for submitting build id also for Dspot or create a completely new dspot scanner to fetch build id, but that's just an add on for now everything is functioning fine :) . 

Regard the configuration, do you mean my "with_dspot" travis branch pom.xml ?. I just followed [your doc](https://github.com/STAMP-project/dspot) and configured it that way and it seems to be working just fine for me running dspot as maven plugin. Maybe I misunderstood something, please enlighten me if that's the case :) .

Best

**Comment by monperrus** [comment]
Thanks for the progress. I would suggest to make baby pull requests. The first one could only contain a `Dockerfile` in order to run Dspot through docker. WDYT?

**Comment by Tailp** [comment]
Sorry for the late answer :) . It will be done in a new PR . Since I will re-fork this and make a new PR.

**Comment by monperrus** [comment]
This continues in #841

**Pull request closed without merging**
