### PR TITLE
Unspecify assertions

### PR DESCRIPTION
**Pull request by sbihel**

### CODE REVIEW

**Comment by sbihel** [comment]
I am confused, on my machine I need to remove the comments for the tests to pass

**Comment by danglotb** [comment]
Hi @sbihel 

I think the problem come from the order of the execution of tests, which is very bad.

In your machine, you have a specific order, and on travis there is another one. So the boolean `withComment` is probably set to `true` by another one, executed before of travis, but after on your machine. I'm gonna look for this.

Anyway, thank you for the PR, it seems very good!

**Comment by sbihel** [comment]
Should I refactor all similar tests also?

**Comment by danglotb** [comment]
@sbihel If you run only the test class `fr.inria.diversify.dspot.amplifier.StatementAddTest`, did it pass or not?

**Comment by sbihel** [comment]
@danglotb no problem with only `StatementAddTest` or `StatementAddTest,AssertGeneratorHelperTest` or `AssertGeneratorHelperTest,StatementAddTest` but it fails with `StatementAddTest,MethodsAssertGeneratorTest` and `MethodsAssertGeneratorTest,StatementAddTest`.

The order given to `-Dtest=` isn't taken into account?

**Comment by danglotb** [comment]
> The order given to `-Dtest=` isn't taken into account?

I don't know about that, but anyway, all the tests should pass, in any order there are executed.

> I am confused, on my machine I need to remove the comments for the tests to pass

This is also confusing me. I was wrong when I talked about the `DSpotUtils#withComment` boolean. In any case, the comments should be attached to the added statements / generated assertions. This boolean only the printing of the comments, not the adding in the spoon model.

I don't understand what is going on. Could you please, provide me a new log, with your changes that should makes some tests pass, from the maven execution of the test, _i.e._ `mvn test` ?

**Comment by danglotb** [comment]
@sbihel Can we merge this PR?

**Comment by sbihel** [comment]
@danglotb I guess so. There might be similar tests that could use this refactoring but we can change them later on.

**Comment by danglotb** [comment]
Hi @sbihel. 
> There might be similar tests that could use this refactoring but we can change them later on.

You are probably right, but I will merge this PR first, and then we will take care of the others.

**Comment by danglotb** [comment]
Moreover, it seems that #432 is failing because of this. Thank you!

**Pull request merged**
