### PR TITLE
chore: bump spoon version

### PR DESCRIPTION
**Pull request by danglotb**

### CODE REVIEW

**Comment by danglotb** [comment]
Looks like there are problems with 
`CompilationUnit cu = this.getFactory().CompilationUnit().getOrCreate(element);` in `JavaOutputProcessor` when printing a java file with Spoon.

**Comment by monperrus** [comment]
We're still stabilizing 7.6. Let's wait a little bit.

**Comment by monperrus** [comment]
conflict?

**Comment by monperrus** [comment]
ping  @danglotb

**Comment by danglotb** [comment]
Hello, there are still issues with the CompilationUnit. It seems that it returns the original version of the class when I try to print it with : 

```java
public static void printCtTypeToGivenDirectory(CtType<?> type, File directory, boolean autoImports) {
         try {
            Factory factory = type.getFactory();
            Environment env = factory.getEnvironment();
            env.setAutoImports(autoImports);
            env.setNoClasspath(true);
            env.setCommentEnabled(DSpotUtils.withComment);
            JavaOutputProcessor processor = new JavaOutputProcessor(new DefaultJavaPrettyPrinter(env));
            processor.setFactory(factory);
            processor.getEnvironment().setSourceOutputDirectory(directory);
            processor.createJavaFile(type);
            env.setAutoImports(false);
        } catch (Exception e) {
            printCtTypUsingToStringToGivenDirectory(type, directory);
        }
```

In `processor#createJavaFile(CtElement)` there is:

```java
CompilationUnit cu = this.getFactory().CompilationUnit().getOrCreate(element);
```

And this CompilationUnit still point on the original class and not the one that I want to print, _i.e._ the `element` gave in parameter.

I tried to create a new Factory (kind of messy & ugly but uh), as follow:

```java
try {
            //Factory factory = type.getFactory();
            Environment env = type.getFactory().getEnvironment();
            Factory factory = new FactoryImpl(new DefaultCoreFactory(), env);
            CtPackage packageOfTestClass = factory.Package().getOrCreate(type.getPackage().getQualifiedName());
            packageOfTestClass.addType(type);
            env.setAutoImports(autoImports);
            env.setNoClasspath(true);
            env.setCommentEnabled(DSpotUtils.withComment);
            JavaOutputProcessor processor = new JavaOutputProcessor(new DefaultJavaPrettyPrinter(env));
            processor.setFactory(factory);
            processor.getEnvironment().setSourceOutputDirectory(directory);
            processor.createJavaFile(type);
            env.setAutoImports(false);
        } catch (Exception e) {
            printCtTypUsingToStringToGivenDirectory(type, directory);
        }
```

But still the same behaviour. It looks like Spoon is using the original java file to print it, instead of the loaded CtType.

**Comment by monperrus** [comment]
Great progress. Could you write a pull-request with a failing test case in the Spoon repo?

**Comment by danglotb** [comment]
Hello @monperrus 

Yes, I'll do that ASAP. Thank you :)

**Comment by monperrus** [comment]
updated to 8.1.0-SNAPSHOT

**Comment by danglotb** [comment]
It looks like we have still the same issue. 

Spoon is printing the old class (before modification) instead of the one given in parameter.

BTW, DSpot looks into the [public snapshot repository](http://maven.inria.fr/artifactory/spoon-public-snapshot/fr/inria/gforge/spoon/spoon-core/) at maven.inria.fr for the snapshot of Spoon

However, the last updated is : 
> 8.1.0-SNAPSHOT/      06-Nov-2019 15:51    -

Is the latest SNAPSHOT available somewhere else ?

I'll look at providing a new test as pull request on the spoon repository to capture the problem. 

The cause in DSpot is the following method: 

```java
public static void printCtTypeToGivenDirectory(CtType<?> type, File directory, boolean autoImports) {
        Environment env = type.getFactory().getEnvironment();
        Factory factory = new FactoryImpl(new DefaultCoreFactory(), env);
        try {
            //Factory factory = type.getFactory();
            CtPackage packageOfTestClass = factory.Package().create(factory.Package().getRootPackage(), type.getPackage().getQualifiedName());
            packageOfTestClass.addType(type.clone());
            env.setAutoImports(autoImports);
            env.setNoClasspath(true);
            env.setCommentEnabled(DSpotUtils.withComment);
            JavaOutputProcessor processor = new JavaOutputProcessor(new DefaultJavaPrettyPrinter(env));
            processor.setFactory(factory);
            processor.getEnvironment().setSourceOutputDirectory(directory);
            processor.createJavaFile(type);
            env.setAutoImports(false);
        } catch (Exception e) {
            printCtTypUsingToStringToGivenDirectory(type, directory);
        }
    }
```

Thank you very much.

**Comment by monperrus** [comment]
> DSpot looks into the public snapshot repository at maven.inria.fr for the snapshot of Spoon

Yes, and the last update is from Feb 26, if you look into the `8.1.0-SNAPSHOT` folder:
http://maven.inria.fr/artifactory/spoon-public-snapshot/fr/inria/gforge/spoon/spoon-core/8.1.0-SNAPSHOT/

**Comment by monperrus** [comment]
Thanks a lot @danglotb !

**Pull request merged**
