### PR TITLE
Optimization#4 Optimal management of dictionaries for holding cloned CtClass and CtMethod without memory leaks

### PR DESCRIPTION
**Pull request by jesus-gorronogoitia**
This optimization manages optimally the dictionaries that hold references of CtMethods to parents and original ones. It also introduces some memory optimization to enable GC to dispose of cloned CtMethods that are not required in the scope, particularly before the amplified class is serialized to output folder.
Before this optimization, this is a memory consumption series
image
After this optimization, the same DSpot experiment shows this memory consumption series
image
which is better, although not much better. The important point is that for long DSpot runs there won't be memory leaks, and that before the amplify class is serialized (which takes high amounts of memory) the memory used so far that is not required is released.

### CODE REVIEW

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

Thank you very much for this, this is awesome!

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb TravisCI work fails when running DSpot tests, but they seems to be related to some wrong Enums, not related to this PR. Could you please check them? If you think this failures could be related to this PR, let me know, and I will investigate. Otherwise, let me know how to proceed.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb Let me know when you have time if the tests issues that TravisCI are reporting are failing because the changes introduced in this PR, as commented in my previous message.

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

I'm looking at this, it must be included in the next release.

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

I have the following error message: `The job exceeded the maximum log length, and has been terminated.`. 

It seems that we must reduce the traces to make it pass on Travis.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
I didn't add new logs to the code, so I don know what to do. Maybe we can have a look together during the workshop session. Besides, I see different Maven building errors in TravisCI, are they relevant? They seem to break the build

**Comment by danglotb** [comment]
I pulled your branch, and rebase with recent changes on the master.

It seems that my changes made this error.

> Maybe we can have a look together during the workshop session. 

Yes, we could. But maybe there is something else to do. I think I can resolve this issue on my own.

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

I make the test suite passes on your changes, see my [travis](https://travis-ci.org/danglotb/dspot/)

There are two major changes to do:
1. reset the cache when the `InputConfiguration` is reinitialized. For the clients, it is not required, but in the test suite, one must remove the state left by the test.
2. register test methods used in `eu.stamp_project.test_framework.TestFrameworkTest` in the map of original bounds you introduced.

For now, I cannot merge automatically my changes into your pull request, but I'll prepare a clean pull request ASAP.

Thank you.

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

I opened on your fork a pull request to incorporate the changes proposed in my previous comment.

See it [here](https://github.com/jesus-gorronogoitia/dspot/pull/2).

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb Done, I've accepted your PR. Thanks.

**Comment by danglotb** [comment]
Something went wrong. Some commits are duplicated. Thus, I have introduced a bug in the test suite. I'm looking for a possible solution.

**Comment by jesus-gorronogoitia** [comment]
New pull request created by @danglotb fixing this one. Closing.

**Pull request closed without merging**
