### PR TITLE
fixes for Jenkins: relative path, file separator, class loading

### PR DESCRIPTION
**Pull request by spookyvale**
some changes to improve compatibility when used under Windows and in Jenkins environment.
Mainly it avoids the creation of files with relative paths, generalizes the file separator depending on the OS and tries a different class loader when the original one fails.

### CODE REVIEW

**Comment by danglotb** [comment]
Hi @spookyvale, please rebase your branch.

**Comment by spookyvale** [comment]
@danglotb do you have any idea why the build might fail? 
In travis, reading the log, I see the error is in the MethodAssertGeneration. 
It says that ObjectLog cannot be resolved but I cannot think of a change that might have an impact on this.

**Comment by danglotb** [comment]
Hi @spookyvale 
It seems that your forgot to update some paths. I saw a lot of errors and redundancies in the code I will fix everything soon.

But for now, we can add 
`InputConfiguration().get().getAbsolutePathToProjectRoot()` [here](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/eu/stamp_project/utils/compilation/TestRunner.java#L37) and [here](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/eu/stamp_project/utils/compilation/TestRunner.java#L61), _i.e._, change
` AmplificationHelper.PATH_SEPARATOR + new File("target/dspot/dependencies/").getAbsolutePath()` by
`InputConfiguration().get().getAbsolutePathToProjectRoot() + File.separator + "target/dspot/dependencies/"`.
Thank you.

**Comment by spookyvale** [comment]
I already performed the changes in TestRunner class (locally) but I did not solve the problem. 
I am trying to find other relative paths. I'll keep you updated

**Comment by danglotb** [comment]
I openned a PR on your own fork: [spookyvale/dspot/#3](https://github.com/spookyvale/dspot/pull/3). We can merge this one after mine. Thank you very much!

**Comment by danglotb** [comment]
merged, thank you!

**Pull request merged**
