### PR TITLE
Refactor Main, DSpot and Amplification

### PR DESCRIPTION
**Pull request by andrewbwogi**

### CODE REVIEW

**Comment by andrewbwogi** [comment]
Hi @danglotb, eu.stamp_project.utils.DSpotUtilsTest is failing for me with f737ce01c3496686a702d13698eb34b4d936829c. Is the expected value in testWithLombokAnnotation() correct?

**Comment by danglotb** [comment]
Hello @andrewbwogi 

Thank you for your PR. Yes, it seems that I may wrongly updated an expected value in the `DSpotUtilsTest`.

I'm looking at it.

**Comment by danglotb** [comment]
Hello @andrewbwogi 

To resolve the conflict, we must move the new code 

```java
if (testMethodsToBeAmplifiedNames.size() == 1 &&
                testMethodsToBeAmplifiedNames.get(0).isEmpty()) {
            testMethodsToBeAmplifiedNames.clear();
        }
```

from the Main class to the new location. Could you take care of that?

There is also a failing test on `dspot-diff-test-selection`. According to the trace, resolving the conflict would fix the test.

Thank you.

**Comment by danglotb** [comment]
Hello @andrewbwogi 

Because we are bit in a hurry, I close this one and merge the one that I opened #928 

I won't squash the commits in order to keep your authorship.

Best.

**Pull request closed without merging**
