### PR TITLE
Json report

### PR DESCRIPTION
**Pull request by danglotb**
```json
{
	"test7_cf141":{
		"#AssertionAdded":3,
		"#InputAdded":3,
		"#MutantKilled":1,
		"MutantsKilled":[
			{
				"ID":"org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_ORDER_ELSE",
				"lineNumber":"12",
				"location":"charAt"
			}
		]
	},
	"test2_cf42":{
		"#AssertionAdded":3,
		"#InputAdded":3,
		"#MutantKilled":1,
		"MutantsKilled":[
			{
				"ID":"org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_ORDER_ELSE",
				"lineNumber":"12",
				"location":"charAt"
			}
		]
	}
}
```

### CODE REVIEW

**Comment by danglotb** [comment]
I propose to order the json file by the ratio nbMutantKilled / (NbInput + NbAssert).

**Comment by danglotb** [comment]
Maybe, we should also point out, which generated test kill mutant than others does not kill or eliminate mutant that are killed (such as those killed by the manual test suite).

**Comment by bbaudry** [comment]
Yes, I agree, it would be great to know which test case kills some new mutants.
For the mutants that are killed by the manual test suite, I'm less convinced: it can still be interesting to know if a variant of a manual test kills the same mutants as the original test, or if we generate test cases that either 'subsume' several existing tests (kill all the mutants killed by a set of test cases) or if we generate 'surgical' tests (that kill only specific mutants that are otherwise killed by only one or two existing test cases)

**Comment by danglotb** [comment]
>  it would be great to know which test case kills some new mutants.

Actually, the `PitMutantScoreSelector` keeps only new test cases that kill mutant that the manual tests do not kill.

> For the mutants that are killed by the manual test suite, I'm less convinced: it can still be interesting to know if a variant of a manual test kills the same mutants as the original test, or if we generate test cases that either 'subsume' several existing tests 

But, this point of view is very interesting, I'll update the selector in that way.

For the output, I think to add another json file, with all generated test cases, that way we can parse the first report, and retrieve test cases that we want in the second one. (And why not after that, add it automatically to the manual test suite)

also I'll add as root, the class of the generated test cases such as:
```json
{	
	"example.TestSuiteExample": [
		{
			"test7_cf141":{
				"#AssertionAdded":3,
				"#InputAdded":3,
				"#MutantKilled":1,
				"MutantsKilled":[
					{
						"ID":"org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_ORDER_ELSE",
						"lineNumber":"12",
						"location":"charAt"
					}
				]
			},
			"test2_cf42":{
				"#AssertionAdded":3,
				"#InputAdded":3,
				"#MutantKilled":1,
				"MutantsKilled":[
					{
						"ID":"org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_ORDER_ELSE",
						"lineNumber":"12",
						"location":"charAt"
					}
				]
			}
		}
	]
}
```

**Comment by danglotb** [comment]
It now produces: 
* the json file with all mutants(see above)
* and a class named _MyTestClass_ Ampl, with all amplified tests.
* a report.txt which is the report in the stdout

**Pull request merged**
