### PR TITLE
RandomBudgetizer: DSpot time execution optimization

### PR DESCRIPTION
**Pull request by jesus-gorronogoitia**
This PR creates a  budgetizer that randomly chooses  the amplified methods to be kept up to the limit when this limit is exceeded. 
This budgetizer is configured as default, replacing the NoBudgetizer, which is renamed as TextualDistanceBudgetizer.
In experiments (see report below), overall execution time improvement ranges from 6% to 33%.
Obtained results are quite similar, as reported below.

Report on experiments:
```
Experiment with DSpot random reduce method in Dhell project
------------------------------------------
DSpot command: java -Xms2048m -Xmx4096m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/yosu/Projects/STAMP/Git/dhell/dspot_dump.bin -jar $dspotJar --path-to-properties $dspotPropertiesFile -i 3 --test all -a MethodAdd:AllLiteralAmplifiers:MethodGeneratorAmplifier -s JacocoCoverageSelector --verbose --clean --tests-reduce-method=random

A) JacocoCoverageSelector

A.1) tests-reduce-method=textual_distance
Elapsed time 824662 ms

Initial instruction coverage: 560 / 1077
52.00%
Amplification results with 592 amplified tests.
Amplified instruction coverage: 708 / 1077
65.74%

Initial instruction coverage: 294 / 1077
27.30%
Amplification results with 254 amplified tests.
Amplified instruction coverage: 370 / 1077
34.35%

A.2) tests-reduce-method=random

Elapsed time 771547 ms


Initial instruction coverage: 560 / 1077
52.00%
Amplification results with 819 amplified tests.
Amplified instruction coverage: 706 / 1077
65.55%

Initial instruction coverage: 294 / 1077
27.30%
Amplification results with 383 amplified tests.
Amplified instruction coverage: 375 / 1077
34.82%

Execution time overall improvement: 6,4%

A) PITSelector

A.1) tests-reduce-method=textual_distance

Elapsed time 1445128 ms

Test class that has been amplified: eu.stamp_project.examples.dhell.HelloAppTest
The original test suite kills 16 mutants
The amplification results with 1 new tests
it kills 4 more mutants

Test class that has been amplified: eu.stamp_project.examples.dhell.MyStorageTest
The original test suite kills 16 mutants
The amplification results with 12 new tests
it kills 2 more mutants


A.2) tests-reduce-method=random

Elapsed time 956492 ms

Test class that has been amplified: eu.stamp_project.examples.dhell.HelloAppTest
The original test suite kills 16 mutants
The amplification results with 1 new tests
it kills 4 more mutants

Test class that has been amplified: eu.stamp_project.examples.dhell.MyStorageTest
The original test suite kills 16 mutants
The amplification results with 10 new tests
it kills 2 more mutants

Execution time overall improvement: 33,81%
```

### CODE REVIEW

**Comment by jesus-gorronogoitia** [comment]
Bonjour @danglotb It seems there is one test failing in TravisCI, but it is not easy to see which one and the reason. Could you please have a look and tell me if it is caused by my changes. Merci

**Comment by danglotb** [comment]
I opened a pull request on your fork: jesus-gorronogoitia/dspot#3

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb Accepted your pull requests, thanks.

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

The changes are good to me. Ready to merge?

**Comment by jesus-gorronogoitia** [comment]
Ok, thanks

On 7/5/19 11:59, Benjamin DANGLOT wrote:

Hi @jesus-gorronogoitia<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjesus-gorronogoitia&data=02%7C01%7Cjesus.gorronogoitia%40atos.net%7C0ba467840286451f2fa008d6d2d2c23f%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C636928199971153742&sdata=TyKGuVpC4LWpEsFu4zRgl9Bwx5H%2FjnoOQHUPxmLC65Y%3D&reserved=0>

The changes are good to me. Ready to merge?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSTAMP-project%2Fdspot%2Fpull%2F774%23issuecomment-490017017&data=02%7C01%7Cjesus.gorronogoitia%40atos.net%7C0ba467840286451f2fa008d6d2d2c23f%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C636928199971163751&sdata=oaaYU9kO8KAO8ihAKL8gKd7PWs5zJBxcB6%2F9sj%2FBtDM%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA35ES2FPVZVREROFHKPOZTPUFHIHANCNFSM4HIENCXA&data=02%7C01%7Cjesus.gorronogoitia%40atos.net%7C0ba467840286451f2fa008d6d2d2c23f%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C636928199971163751&sdata=nOFZbohEW706YXbp6QBcV11mFP2o%2FOocnCJ11nGdlYw%3D&reserved=0>.

This e-mail and the documents attached are confidential and intended solely for the addressee; it may also be privileged. If you receive this e-mail in error, please notify the sender immediately and destroy it.
As its integrity cannot be secured on the Internet, the Atos group liability cannot be triggered for the message content. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.

Este mensaje y los ficheros adjuntos pueden contener información confidencial destinada solamente a la(s) persona(s) mencionadas anteriormente y pueden estar protegidos por secreto profesional.
Si usted recibe este correo electrónico por error, gracias por informar inmediatamente al remitente y destruir el mensaje.
Al no estar asegurada la integridad de este mensaje sobre la red, Atos no se hace responsable por su contenido. Su contenido no constituye ningún compromiso para el grupo Atos, salvo ratificación escrita por ambas partes.
Aunque se esfuerza al máximo por mantener su red libre de virus, el emisor no puede garantizar nada al respecto y no será responsable de cualesquiera daños que puedan resultar de una transmisión de virus.

**Pull request merged**
