### PR TITLE
Gradle projects descartes mutators selection

### PR DESCRIPTION
**Pull request by danzone**
Hello @danglotb ,
    I've added the possibility to use Descartes mutators, specifying them in the project properties file. I preferred this way because at the moment it seems to me more practical, given the possibility to select several mutator types and values. Of course this can change in the future, passing them as command line options. With this last change we have covered all the options for Gradle projects: Evosuite and  Descartes.

### CODE REVIEW

**Comment by danglotb** [comment]
Hello @danzone 

Thank you very much, it seems great!

> I preferred this way because at the moment it seems to me more practical, given the possibility to select several mutator types and values

I agree with you.

About the builds, it is because the configuration of the maven home of travis changed. I'll fix it in #174 

Cheers :)

**Comment by danglotb** [comment]
Hello @danzone 

I propose you to rebase your branch with new changes on master in order to make travis pass.

Cheers! :)

**Comment by danzone** [comment]
Hello @danglotb , I rebased my branch. Everything should be ok. Travis build failed first time on PitTest test case, but it succeded on a subsequent execution (don't know why).

**Comment by danglotb** [comment]
Hello @danzone 

Yeah, some tests are flaky and i don't know why either :s

Thank for changes!

**Pull request merged**
