### PR TITLE
ci: bump the version of pit used in the GradleBuilder

### PR DESCRIPTION
**Pull request by danglotb**

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks @danglotb any idea about the failure?

**Comment by danglotb** [comment]
I'm stuck here, I found a workaround which is to upgrade the version of pit in the `build.gradle` and use `Plugins {}` directives instead of `buildscript {}` but the Gradle API (that we use internally in DSpot) does not support this format.

I will fix this or find another way to do it ASAP.

**Comment by monperrus** [comment]
super, thanks.

**Comment by danglotb** [comment]
I removed the dependency to `gradle-api` and use a java `Process` to do the job. It is not the best, but I guess it does the job. I would love to remove the dpot dependency to any tools as Maven or Gradle.

Working on the update of tests to make them pass ASAP.

**Comment by monperrus** [comment]
cool, thanks Benjamin.

**Pull request closed without merging**
