### PR TITLE
PR for Context2Name

### LINKED ISSUE #830: add support for semantic naming of new variables
We could use machine learning to predict good names for new variables in amplified tests

See Context2Name: A Deep Learning-Based Approach to Infer Natural Variable Names from Usage Contexts
https://arxiv.org/abs/1809.05193

### PR DESCRIPTION
**Pull request by jaxxgu**
fix #830

### CODE REVIEW

**Comment by ycaxgjd** [comment]
for issue #830

**Comment by jaxxgu** [comment]
Currently we are using one weak model, I plan to train and upload one better model in another PR. The rest has been completed.

**Comment by monperrus** [comment]
We'd like to see the difference in the test case, something like,

assertEquals("void test() { a=3;} }", dspotWithoutC2N);
assertEquals("void test() { betterName=3;} }", dspotWithoutC2N);

**Comment by jaxxgu** [comment]
I can not upload model files, both via Git or webpage, as they are too large.
I guess context2name test file may not be able to get passed, so I need to add one Ignore annotation in the test file.

**Comment by monperrus** [comment]
What's the size of the default model?

**Comment by jaxxgu** [comment]
260MB, the size limit is 100MB

**Comment by jaxxgu** [comment]
The large model file have been splitted into small size ones, and they will get combined into the original big one automatically when necessary. (Git LFS is not one practical option)

**Comment by monperrus** [comment]
Instead, I would suggest to host the 260MB somewhere else on the web (for example under your KTH public_html) and download it during CI setup. WDYT?

**Comment by jaxxgu** [comment]
It should be better as the repo size can get reduced in this manner. I plan to try this idea when we have trained one better model.

**Comment by jaxxgu** [comment]
Or maybe we could tag and release repo periodically, then upload and attach some large files such as this model file as assets. In that case, there seems no size limit. By this way, all large files are still at the same place with corresponding code files.

**Comment by monperrus** [comment]
> then upload and attach some large files such as this model file as assets


very good idea. created https://github.com/STAMP-project/data/ for this and added you as
collaborator. could you upload the model there?

**Comment by jaxxgu** [comment]
Uploaded. I will replace current "split/cat" method with your "upload/download" method soon.

**Comment by jaxxgu** [comment]
I located two failing test cases, and they are affected by new CI environment. Right now I added Ignore annotations for both of them.

These two cases can not recur locally. I believe it is caused by JUnit parallel execution.

**Comment by monperrus** [comment]
conflict in `.travis.yml` to merge

**Comment by monperrus** [comment]
@danglotb putting the conflict aside and the change in assertions, are you OK to merge this one?

**Comment by jaxxgu** [comment]
> conflict in `.travis.yml` to merge

Solved.

**Comment by danglotb** [comment]
It looks great! Thank you very much for this work.

However, I would like two small modifications:

1. remove all the comment that useless, _e.g._  completely commented methods.
2. replace all the `\n` by the system line separator, or by `AmplificationHelper.LINE_SEPARATOR`

I'm gonna look at those two test cases that are failing.

**Comment by jaxxgu** [comment]
Hey @danglotb 
I have removed commented methods and useless files, and also replaced '\n' with AmplificationHelper.LINE_SEPARATOR

**Comment by monperrus** [comment]
LGTM ping @danglotb for merging

**Comment by monperrus** [comment]
Thanks a lot @jaxxgu

**Pull request merged**
